version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kz123456
    ports:
      - "5433:5432"
  app:
    image: spring_boot
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Kz123456
    ports:
      - "8081:8888"
    depends_on:
      - db
