version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kz123456
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  springboot:
    build: .
    container_name: springboot
    depends_on:
      - postgres
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/spring
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: Kz123456
volumes:
  postgres-data: